name: Build
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        id: cache-yarn
        uses: actions/cache@v3
        env:
          cache-name: cache-node-module
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - if: steps.cache-yarn.outputs.cache-hit != 'true'
        name: 📦 Install Dependencies
        env:
          NO_YARN_POSTINSTALL: 1
        run: yarn install --frozen-lockfile
